import { ProfileResults } from '../models/ProfileResults';
const Experiences = [
  {
    jobTitle: 'Auxiliar administrativo',
    companyTitle: 'Luiz Carlos Rossini Ltda.',
    duration: '3 yrs 6 mos',
    company: {},
  },
  {
    jobTitle: 'Desenvolvedor de Software Júnior - Trainee - Estágio (System Analyst)',
    companyTitle: 'Unisys',
    duration: '2 yrs',
    company: {
      name: 'Unisys',
      description:
        'Unisys is a global technology solutions company that provides IT services, software, and technology to clients in the government, financial services, and commercial markets. Their offerings include security solutions, advanced data analytics, cloud and...',
      employeesRange: '10K-50K',
      raised: null,
      tags: [
        'Information Technology & Services',
        'Computer Programming',
        'Software',
        'Professional Services',
        'Computers',
        'E-commerce',
        'Design Services',
        'Integration Services',
        'IT Management',
        'Technology',
        'Consulting & Professional Services',
        'B2B',
        'B2C',
        'Enterprise',
        'SAAS',
        'ISP',
      ],
      category: {
        sector: 'Information Technology',
        industryGroup: 'Software & Services',
        industry: 'Internet Software & Services',
        subIndustry: 'Internet Software & Services',
        gicsCode: '45102010',
        sicCode: '73',
        sic4Codes: ['7371', '7379'],
        naicsCode: '54',
        naics6Codes: ['541511', '541512'],
        naics6Codes2022: ['541511', '541512'],
      },
      tech: [
        'outlook',
        'vimeo',
        'microsoft_exchange_online',
        'sendgrid',
        'optimizely',
        'google_tag_manager',
        'aws_route_53',
        'microsoft_office_365',
        'cloud_flare',
        'qualified',
        'twitter_button',
        'bing_advertiser',
        'google_analytics',
        'iterable',
        'facebook_advertiser',
        'hotjar',
        'demandbase',
        'adroll',
        'db2',
        'grafana',
        'oracle_crm',
        'smartsheet',
        'sybase',
        'apache_kafka',
        'informatica',
        'sage_50cloud',
        'splunk',
        'microsoft_team_foundation_server',
        'stripe',
        'oracle_endeca',
        'appnexus',
        'apache_http_server',
        'ibm_infosphere',
        'nice_incontact',
        'couchbase',
        'atlassian_fisheye',
        'gitlab',
        'dropbox',
        'workamajig',
        'workday',
        'sas_enterprise',
        'oracle_cash_and_treasury_management',
        'qliktech',
        'oracle_peoplesoft',
        'flexera_software',
        'entrust',
        'tibco_spotfire',
        'oracle_data_integrator',
        'trello',
        'ibm_websphere',
        'ibm_lotus_notes',
        'sap_concur',
        'rabbitmq',
        'cision',
        'cloudera',
        'apache_hadoop',
        'couchdb',
        'dstillery',
        'oracle_business_intelligence',
        'aws_dynamodb',
        'oracle_weblogic',
        'aws_cloudwatch',
        'atlassian_confluence',
        'oracle_hyperion',
        'mediamath',
        'kentico',
        'microsoft_dynamics',
        'hootsuite',
        'quickbooks',
        'sap_crystal_reports',
        'tibco_ems',
        'apache_tomcat',
        'microsoft_sql_server',
        'hp_servers',
        'hbase',
        'basecamp',
        'podio',
        'snaplogic',
        'okta',
        'the_trade_desk',
        'fortinet',
        'mongodb',
        'microsoft_project',
        'ibm_cognos',
        'pubmatic',
        'ibm_infosphere_datastage',
        'alteryx',
        'sas_data_integration',
        'episerver',
        'peoplesoft_crm',
        'pentaho',
        'goldengate',
        'sap_sales_order_management',
        'jaspersoft',
        'aws_kinesis',
        'jahia',
        'nimsoft',
        'microsoft_teams',
        'sap_business_objects',
        'tibco_rendezvous',
        'apache_spark',
        'sprinklr',
        'qlikview',
        'ibm_lotus_domino',
        'salesforce',
        'atlassian_crucible',
        'sugarcrm',
        'aws_redshift',
        'sailpoint',
        'statcounter',
        'teradata',
        'sage_crm',
        'aws_lambda',
        'google_search_appliance',
        'webmethods',
        'bluekai',
        'acxiom',
        'palo_alto_networks',
        'pivotal_tracker',
        'github',
        'rsa_securid',
        'zoho_crm',
        'goldmine',
        'microstrategy',
        'oracle_fusion',
        'sap_hana',
        'matomo',
        'netsuite_crm',
        'oracle_essbase',
        'liferay',
        'information_builders',
        'apache_maven',
        'netsuite',
        'talend',
        'twilio',
        'kronos',
        'peoplesoft_sales',
        'postgresql',
        'gotomeeting',
        'mysql',
        'windows_server',
        'sitefinity',
        'oracle_application_server',
        'servicenow',
        'snowflake',
        'adobe_marketing_cloud',
        'quest_foglight',
        'microsoft_power_bi',
        'sap_crm',
        'cyberark',
        'factset',
        'qradar',
        'netsuite_suitecommerce',
        'aggregate_knowledge',
        'atlassian_jira',
        'facebook_workplace',
        'neo4j',
        'openid',
        'hive',
        'filemaker_pro',
        'apache_cassandra',
        'vmware_server',
        'sap_human_capital_management',
      ],
      techCategories: [
        'email_hosting_service',
        'image_video_services',
        'email_delivery_service',
        'website_optimization',
        'tag_management',
        'dns',
        'productivity',
        'social_sharing',
        'advertising',
        'analytics',
        'marketing_automation',
        'account_based_marketing',
        'database',
        'monitoring',
        'crm',
        'data_processing',
        'data_management',
        'accounting_and_finance',
        'project_management_software',
        'payment',
        'web_servers',
        'customer_support',
        'human_capital_management',
        'business_management',
        'security',
        'content_management_system',
        'adverstising',
        'data_visualization',
        'cloud_computing_services',
        'sales_productivity',
        'ecommerce',
      ],
      domainName: 'unisys.com',
    },
  },
  {
    jobTitle: 'Tech Lead',
    companyTitle: 'GLOBAL HITSS',
    duration: '1 yr 3 mos',
    company: {
      name: 'Global Hitss',
      description:
        'Globalhitss is a company that provides high performance IT solutions and services, with a focus on digital solutions and IT services in Latin America and the United States.',
      employeesRange: '10K-50K',
      raised: null,
      tags: [
        'Computer Programming',
        'Software',
        'Professional Services',
        'Computers',
        'E-commerce',
        'Consulting & Professional Services',
        'Information Technology & Services',
        'B2B',
        'B2C',
        'ISP',
      ],
      category: {
        sector: 'Information Technology',
        industryGroup: 'Software & Services',
        industry: 'Internet Software & Services',
        subIndustry: 'Internet Software & Services',
        gicsCode: '45102010',
        sicCode: '73',
        sic4Codes: ['7371'],
        naicsCode: '54',
        naics6Codes: ['541511'],
        naics6Codes2022: ['541511'],
      },
      tech: [
        'outlook',
        'microsoft_exchange_online',
        'wordpress',
        'centos',
        'google_tag_manager',
        'microsoft_office_365',
        'apache',
        'db2',
        'grafana',
        'oracle_crm',
        'smartsheet',
        'sybase',
        'apache_kafka',
        'splunk',
        'oracle_endeca',
        'informatica',
        'apache_http_server',
        'apache_spark',
        'ibm_infosphere',
        'couchbase',
        'gitlab',
        'dropbox',
        'atlassian_jira',
        'sas_enterprise',
        'qliktech',
        'flexera_software',
        'entrust',
        'tibco_spotfire',
        'oracle_data_integrator',
        'trello',
        'ibm_websphere',
        'ibm_lotus_notes',
        'rabbitmq',
        'cloudera',
        'apache_hadoop',
        'oracle_business_intelligence',
        'aws_dynamodb',
        'oracle_weblogic',
        'aws_cloudwatch',
        'atlassian_confluence',
        'oracle_hyperion',
        'microsoft_dynamics',
        'sap_crystal_reports',
        'oracle_peoplesoft',
        'tibco_ems',
        'apache_tomcat',
        'microsoft_sql_server',
        'hp_servers',
        'hbase',
        'basecamp',
        'fortinet',
        'mongodb',
        'microsoft_project',
        'ibm_cognos',
        'ibm_infosphere_datastage',
        'datadog',
        'alteryx',
        'sas_data_integration',
        'peoplesoft_crm',
        'pentaho',
        'goldengate',
        'sap_sales_order_management',
        'jaspersoft',
        'aws_kinesis',
        'nimsoft',
        'sap_business_objects',
        'tibco_rendezvous',
        'qlikview',
        'ibm_lotus_domino',
        'salesforce',
        'sugarcrm',
        'aws_redshift',
        'sailpoint',
        'teradata',
        'aws_lambda',
        'webmethods',
        'ibm_websphere_commerce',
        'palo_alto_networks',
        'pivotal_tracker',
        'github',
        'microstrategy',
        'oracle_fusion',
        'sap_hana',
        'matomo',
        'quickbooks',
        'oracle_essbase',
        'liferay',
        'information_builders',
        'apache_maven',
        'netsuite',
        'talend',
        'apache_nifi',
        'postgresql',
        'gotomeeting',
        'mysql',
        'windows_server',
        'oracle_application_server',
        'servicenow',
        'cybersource',
        'microsoft_power_bi',
        'sap_crm',
        'cyberark',
        'netsuite_suitecommerce',
        'qradar',
        'neo4j',
        'hive',
        'apache_cassandra',
        'vmware_server',
        'sap_human_capital_management',
      ],
      techCategories: [
        'email_hosting_service',
        'content_management_system',
        'operating_system',
        'tag_management',
        'productivity',
        'web_servers',
        'database',
        'monitoring',
        'crm',
        'data_processing',
        'data_management',
        'project_management_software',
        'analytics',
        'accounting_and_finance',
        'security',
        'business_management',
        'data_visualization',
        'ecommerce',
        'payment',
        'human_capital_management',
      ],
      domainName: 'globalhitss.com',
    },
  },
  {
    jobTitle: 'Desenvolvedor Full Stack Sênior',
    companyTitle: 'Sankhya Gestão De Negócios',
    duration: '5 mos',
    company: {
      name: 'Sankhya Gestão de Negócios',
      description:
        'Sankhya is a Brazilian company that offers business management solutions using information technology to give entrepreneurs total control of their companies. They offer modular, flexible, and customizable systems and services to facilitate decision-mak...',
      employeesRange: '1K-5K',
      raised: null,
      tags: [
        'Software',
        'Publishers',
        'Information',
        'Publishing',
        'Computer Programming',
        'Professional Services',
        'Computers',
        'E-commerce',
        'Information Technology & Services',
        'SAAS',
        'B2C',
        'B2B',
      ],
      category: {
        sector: 'Information Technology',
        industryGroup: 'Software & Services',
        industry: 'Internet Software & Services',
        subIndustry: 'Internet Software & Services',
        gicsCode: '45103010',
        sicCode: '73',
        sic4Codes: ['7372', '7371'],
        naicsCode: '51',
        naics6Codes: ['511210', '541511'],
        naics6Codes2022: ['513210', '541511'],
      },
      tech: [
        'youtube',
        'facebook_advertiser',
        'google_apps',
        'recaptcha',
        'twitter_button',
        'wordpress',
        'google_tag_manager',
        'activecampaign',
        'microsoft_office_365',
        'amazon_s3',
        'facebook_connect',
        'bing_advertiser',
        'google_analytics',
        'hotjar',
        'conversio',
        'db2',
        'grafana',
        'oracle_crm',
        'sybase',
        'appnexus',
        'apache_http_server',
        'gitlab',
        'dropbox',
        'qliktech',
        'oracle_data_integrator',
        'trello',
        'ibm_websphere',
        'rabbitmq',
        'apache_hadoop',
        'oracle_business_intelligence',
        'oracle_weblogic',
        'aws_cloudwatch',
        'mediamath',
        'microsoft_dynamics',
        'sap_crystal_reports',
        'apache_tomcat',
        'informatica',
        'fortinet',
        'mongodb',
        'microsoft_project',
        'ibm_cognos',
        'pubmatic',
        'peoplesoft_crm',
        'pentaho',
        'sap_sales_order_management',
        'jaspersoft',
        'apache_spark',
        'rubicon_project',
        'oracle_peoplesoft',
        'qlikview',
        'salesforce',
        'google_search_appliance',
        'github',
        'microstrategy',
        'quickbooks',
        'unbounce',
        'apache_maven',
        'facebook_conversion_tracking',
        'postgresql',
        'mysql',
        'windows_server',
        'oracle_application_server',
        'cybersource',
        'microsoft_power_bi',
        'aws_iam',
        'sap_crm',
        'netsuite_suitecommerce',
        'atlassian_jira',
        'oracle_hyperion',
        'apache_cassandra',
      ],
      techCategories: [
        'image_video_services',
        'advertising',
        'productivity',
        'authentication_services',
        'social_sharing',
        'content_management_system',
        'tag_management',
        'marketing_automation',
        'cloud_computing_services',
        'analytics',
        'website_optimization',
        'database',
        'monitoring',
        'crm',
        'web_servers',
        'data_management',
        'project_management_software',
        'data_processing',
        'security',
        'accounting_and_finance',
        'data_visualization',
        'business_management',
        'conversion_optimization',
        'payment',
        'ecommerce',
      ],
      domainName: 'sankhya.com.br',
    },
  },
  {
    jobTitle: 'Analista de Projeto Pleno (System Analyst)',
    companyTitle: 'Tata Consultancy Services',
    duration: '1 yr 9 mos',
    company: {
      name: 'Tata Consultancy Services',
      description:
        'Tata Consultancy Services (TCS) is a multinational information technology services, business solutions and consulting company based in India. TCS provides IT services, digital and business solutions to multiple industries and 131 countries.',
      employeesRange: '100K+',
      raised: 50000000,
      tags: [
        'Computer Programming',
        'Software',
        'Professional Services',
        'Computers',
        'E-commerce',
        'Design Services',
        'Integration Services',
        'IT Management',
        'Consulting & Professional Services',
        'Information Technology & Services',
        'B2B',
        'B2C',
        'Enterprise',
        'ISP',
        'SAAS',
      ],
      category: {
        sector: 'Information Technology',
        industryGroup: 'Software & Services',
        industry: 'Internet Software & Services',
        subIndustry: 'Internet Software & Services',
        gicsCode: '45102010',
        sicCode: '73',
        sic4Codes: ['7371', '7379'],
        naicsCode: '54',
        naics6Codes: ['541511', '541512'],
        naics6Codes2022: ['541511', '541512'],
      },
      tech: [
        'marketo',
        'microsoft_office_365',
        'apache',
        'recaptcha',
        'twitter_button',
        'adobe_dynamic_tag_management',
        'google_tag_manager',
      ],
      techCategories: [
        'marketing_automation',
        'productivity',
        'web_servers',
        'authentication_services',
        'social_sharing',
        'tag_management',
      ],
      domainName: 'tcs.com',
    },
  },
  {
    jobTitle: 'Analista Desenvolvedor Sistemas III (System Analyst)',
    companyTitle: 'DXC Technology',
    duration: '1 yr',
    company: {
      name: 'DXC Technology',
      description:
        'DXC Technology is a company that helps global companies run their mission critical systems and operations while modernizing IT, optimizing data architectures, and ensuring security and scalability across public, private and hybrid clouds.',
      employeesRange: '100K+',
      raised: null,
      tags: [
        'Information Technology & Services',
        'IT Management',
        'Technology',
        'Consulting & Professional Services',
        'Cloud Services',
        'Technology Consulting',
        'Advanced Analytics',
        'Analytics',
        'Security',
        'Cloud Solutions',
        'Outsourcing Services',
        'Workforce Management',
        'Computer Programming',
        'Software',
        'Professional Services',
        'Computers',
        'E-commerce',
        'Design Services',
        'Integration Services',
        'B2B',
        'Enterprise',
        'B2C',
        'SAAS',
      ],
      category: {
        sector: 'Information Technology',
        industryGroup: 'Software & Services',
        industry: 'Internet Software & Services',
        subIndustry: 'Internet Software & Services',
        gicsCode: '45102010',
        sicCode: '73',
        sic4Codes: ['7371', '7379'],
        naicsCode: '54',
        naics6Codes: ['541511', '541512'],
        naics6Codes2022: ['541511', '541512'],
      },
      tech: [
        'marketo',
        'twitter_button',
        'adobe_dynamic_tag_management',
        'facebook_advertiser',
        'live_chat',
        'google_tag_manager',
      ],
      techCategories: [
        'marketing_automation',
        'social_sharing',
        'tag_management',
        'advertising',
        'live_chat',
      ],
      domainName: 'dxc.com',
    },
  },
  {
    jobTitle: 'Software Development Specialist',
    companyTitle: 'Inter',
    duration: '1 yr',
    company: {
      name: 'Inter',
      description:
        'Inter Milan is an Italian professional football club based in Milan, Italy. The club was founded in 1908 and has a rich history of success, including 18 Scudetto titles, 7 Coppa Italia titles, and 5 Italian SuperCup titles. The club has also won 3 Cham...',
      employeesRange: '251-1K',
      raised: null,
      tags: ['E-commerce', 'Sporting Goods', 'B2C'],
      category: {
        sector: 'Consumer Discretionary',
        industryGroup: 'Automobiles & Components',
        industry: 'Automotive',
        subIndustry: 'Automotive',
        gicsCode: '25101020',
        sicCode: '27',
        sic4Codes: ['3011', '7534'],
        naicsCode: '32',
        naics6Codes: ['326211', '326212'],
        naics6Codes2022: ['326211', '326212'],
      },
      tech: [
        'outlook',
        'microsoft_exchange_online',
        'salesforce',
        'aws_route_53',
        'contentful',
        'cloud_flare',
        'microsoft_office_365',
        'google_adsense',
        'google_tag_manager',
        'ios',
        'android',
        'facebook_connect',
        'oracle_crm',
        'stripe',
        'apache_hadoop',
        'openx',
        'apache_tomcat',
        'informatica',
        'ibm_cognos',
        'sugarcrm',
        'microsoft_dynamics',
        'sap_business_objects',
        'postgresql',
        'mysql',
        'windows_server',
        'ibm_websphere',
        'magnolia_cms',
        'oracle_hyperion',
      ],
      techCategories: [
        'email_hosting_service',
        'crm',
        'dns',
        'content_management_system',
        'productivity',
        'advertising',
        'tag_management',
        'programming_framework',
        'operating_system',
        'authentication_services',
        'payment',
        'data_processing',
        'web_servers',
        'data_management',
        'analytics',
        'database',
        'business_management',
      ],
      domainName: 'inter.it',
    },
  },
];

describe('Profile Results', () => {
  let profileRes;

  beforeAll(() => {
    profileRes = new ProfileResults(Experiences);
  });

  // test('test getExperienceInMonths function provided 1 yr 3 mos', () => {
  //     expect(profileRes.getExperienceInMonths("1 yr 3 mos")).toEqual(15);
  //   });

  //   test('test getExperienceInMonths function provided 2 yrs', () => {
  //     expect(profileRes.getExperienceInMonths("2 yrs")).toEqual(24);
  //   });

  //   test('test getExperienceInMonths function provided 11 mos', () => {
  //     expect(profileRes.getExperienceInMonths("11 mos")).toEqual(11);
  //   });
  //   test('test getExperienceInMonths function provided null', () => {
  //     expect(profileRes.getExperienceInMonths(null)).toEqual(0);
  //   });
  //   test('test getExperienceInMonths function provided undefined', () => {
  //     expect(profileRes.getExperienceInMonths(undefined)).toEqual(0);
  //   });

  test('test fillDomain function ', () => {
    profileRes.fillDomain();
    expect(profileRes.domain.totalExperience).not.toBeNull();
  });

  //   test('test fillEmployeRange function ', () => {
  //     profileRes.fillEmployeRange()
  //     expect(profileRes.employeeRanges.length).not.toBeNull();
  //   });

  //   test('test fillVentureBacked function ', () => {
  //     profileRes.fillVentureBacked()
  //     expect(profileRes.ventureBackedCompanies.length).not.toBeNull();
  //   });

  //   test('test filljobExperience function ', () => {
  //     profileRes.filljobExperience()
  //     expect(profileRes.jobExperiences.length).not.toBeNull();
  //   });

  // test('test fillCompanyTenure function ', () => {
  //     profileRes.fillCompanyTenure()
  //     console.log(profileRes.companyTenure)
  //     expect(profileRes.companyTenure.averageTenure).not.toBeNull();
  //     expect(profileRes.companyTenure.shortestTenure).not.toBeNull();
  //   });

  // test('test profileRes build func ', () => {
  //     profileRes.build();
  //    expect(profileRes).not.toBeNull();
  //   });

  // test('test formatTenureMessage function provided 3', () => {
  //   expect(profileRes.formatTenureMessage(3)).toEqual("3 mo(s)");
  // });
  // test('test formatTenureMessage function provided 15 ', () => {
  //     expect(profileRes.formatTenureMessage(15)).toEqual("1 yr(s) 3 mo(s)");
  //   });
  // test('test formatTenureMessage function provided 24 ', () => {
  //     expect(profileRes.formatTenureMessage(24)).toEqual("2 yr(s)");
  //   });
});
